version: '3.4'

services:
  db:
    image: postgres:14-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${HUB_DB_NAME}
      - POSTGRES_USER=${HUB_DB_USERNAME}
      - POSTGRES_PASSWORD=${HUB_DB_PASSWORD}
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      #- "443:443" #HTTPS
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/path-to-certs:/etc/nginx/your.domain.tld #HTTPS
      - static:/static

    networks:
      - main
  
  redis:
    image: redis
    networks:
      - main

  app:
    image: public.ecr.aws/enpass/hub-server:latest
    command: sh -c "wait-for db:5432 -- entrypoint.sh"
    env_file: .env

    depends_on:
      - db
      - redis
    expose:
      - "8000"
    volumes:
      - static:/usr/src/app/static/
    hostname: app
    networks:
      - main
    restart: on-failure

volumes:
  static:
  postgres_data:
    external: true

networks:
  main: